<#
.SYNOPSIS
    Interactive launcher for vulnscope. Double-click the desktop shortcut, or
    run .\scan.ps1 from anywhere.

.DESCRIPTION
    Removes the two friction points of the raw command:
      - it always runs from the package folder, so "No module named vulnscope"
        cannot happen;
      - it builds the scope file for you.

    What it deliberately does NOT remove is the authorization step. vulnscope's
    whole safety model is that a target is scanned only because a human asserted
    they were allowed to scan it. So this still asks who authorizes the scan and
    records it, and the target you type becomes the ONLY thing allowed - the
    permanent-deny list (loopback, link-local, cloud metadata) and deny-by-
    default are still enforced underneath.

.PARAMETER Target
    Host(s) to scan. Prompted for if omitted. Space-separate several.

.PARAMETER AuthorizedBy
    Who authorizes this scan. Prompted for if omitted. Required.

.PARAMETER Html
    Also write and open an HTML report.

.EXAMPLE
    .\scan.ps1
    .\scan.ps1 -Target amirslm.com -AuthorizedBy "Amir (own domain)" -Html
#>

[CmdletBinding()]
param(
    [string]$Target,
    [string]$AuthorizedBy,
    [switch]$Html
)

$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
Set-Location $here

function Find-Python {
    # Returns a hashtable @{ Exe=...; Pre=@(...) }. NOT an array: PowerShell
    # unwraps a single-element array on return, so @('python') would come back
    # as the string 'python' and $py[0] would index the letter 'p'. A hashtable
    # cannot be unwrapped, which sidesteps the whole trap.
    foreach ($cmd in 'python', 'py') {
        if (Get-Command $cmd -ErrorAction SilentlyContinue) {
            if ($cmd -eq 'py') { return @{ Exe = 'py'; Pre = @('-3') } }
            return @{ Exe = 'python'; Pre = @() }
        }
    }
    throw "Python was not found on PATH. Install it from python.org, or the Microsoft Store."
}

Write-Host ""
Write-Host "  vulnscope" -ForegroundColor Cyan -NoNewline
Write-Host " - governed, non-intrusive vulnerability assessment" -ForegroundColor DarkGray
Write-Host "  ------------------------------------------------------------" -ForegroundColor DarkGray

# --- target ---
if (-not $Target) {
    Write-Host ""
    $Target = Read-Host "  Target host(s) to scan (space-separated)"
}
$targets = $Target -split '\s+' | Where-Object { $_ }
if (-not $targets) { Write-Host "  No target given. Nothing to do." -ForegroundColor Yellow; return }

# --- authorization (the part that is NOT optional) ---
if (-not $AuthorizedBy) {
    Write-Host ""
    Write-Host "  Only scan systems you are authorized to test." -ForegroundColor Yellow
    Write-Host "  Your own domains, or a host that explicitly permits scanning." -ForegroundColor DarkGray
    $AuthorizedBy = Read-Host "  Who authorizes this scan (your name / engagement)"
}
if (-not $AuthorizedBy.Trim()) {
    Write-Host "  Authorization is required. Aborting." -ForegroundColor Red
    return
}

# --- build a scope file allowing exactly these targets ---
$scopeFile = Join-Path $here 'scope.txt'   # gitignored; regenerated each run
$lines = @("# generated by scan.ps1 $(Get-Date -Format s)")
foreach ($t in $targets) { $lines += "allow $t" }
$lines | Set-Content -Path $scopeFile -Encoding utf8

$py = Find-Python
$scanArgs = @('-m', 'vulnscope', '--scope', $scopeFile, '--authorized-by', $AuthorizedBy) + $targets

if ($Html) {
    $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    $report = Join-Path $here "report-$stamp.html"
    $scanArgs += @('--html', $report)
}

Write-Host ""
Write-Host "  scanning: $($targets -join ', ')" -ForegroundColor DarkGray
Write-Host ""

& $py.Exe @($py.Pre) @scanArgs
$code = $LASTEXITCODE

Write-Host ""
# vulnscope uses exit codes 0-3 for finding severity and 2 for a usage/scope
# error. Those collide, so distinguish them: a scope/usage failure prints its
# own "error:" line to stderr and produces no report. Rather than guess, only
# show a severity verdict for the codes that unambiguously mean findings.
switch ($code) {
    0 { Write-Host "  Result: nothing above informational." -ForegroundColor Green }
    1 { Write-Host "  Result: low / medium findings." -ForegroundColor Cyan }
    2 { Write-Host "  Result: high findings, or a scope/usage error - read the output above." -ForegroundColor Yellow }
    3 { Write-Host "  Result: CRITICAL findings - act now." -ForegroundColor Red }
    default { Write-Host "  vulnscope exited with code $code." -ForegroundColor Yellow }
}

if ($Html -and (Test-Path $report)) {
    Write-Host "  report: $report" -ForegroundColor DarkGray
    Start-Process $report
}

# The desktop shortcut launches with -NoExit, so the window stays open at a
# prompt after the scan - no manual pause needed, and you can run another scan
# straight away. When called with explicit params (scripted), it just returns.
Write-Host ""
if (-not $PSBoundParameters.ContainsKey('Target')) {
    Write-Host "  Scan again:  .\scan.ps1        (or just re-run the desktop shortcut)" -ForegroundColor DarkGray
    Write-Host "  With report: .\scan.ps1 -Html" -ForegroundColor DarkGray
}
